-- 00_database_setup.sql
-- One-time setup of role, warehouse, database, and schema for the Monogram Paris ETL.
-- Idempotent: safe to re-run.

USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS INGEST
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE
    COMMENT = 'Warehouse for ETL ingestion and dbt transformations';

CREATE DATABASE IF NOT EXISTS INGEST
    COMMENT = 'Monogram Paris luxury vintage fashion data warehouse';

CREATE SCHEMA IF NOT EXISTS INGEST.INGEST
    COMMENT = 'Raw layer — transactional + reference tables loaded by Python ingesters';

CREATE SCHEMA IF NOT EXISTS INGEST.STAGING
    COMMENT = 'Staging layer — dbt models applying light cleaning and casting';

CREATE SCHEMA IF NOT EXISTS INGEST.MARTS
    COMMENT = 'Mart layer — dbt-built star schema (facts + conformed dimensions)';

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS INGEST
    COMMENT = 'Role used by Python ingesters and dbt for the Monogram Paris pipeline';

GRANT USAGE ON WAREHOUSE INGEST TO ROLE INGEST;
GRANT USAGE ON DATABASE INGEST TO ROLE INGEST;
GRANT USAGE ON SCHEMA INGEST.INGEST TO ROLE INGEST;
GRANT USAGE ON SCHEMA INGEST.STAGING TO ROLE INGEST;
GRANT USAGE ON SCHEMA INGEST.MARTS TO ROLE INGEST;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE ON SCHEMA INGEST.INGEST TO ROLE INGEST;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA INGEST.STAGING TO ROLE INGEST;
GRANT CREATE TABLE, CREATE VIEW ON SCHEMA INGEST.MARTS TO ROLE INGEST;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA INGEST.INGEST TO ROLE INGEST;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA INGEST.INGEST TO ROLE INGEST;
