-- 01_raw_transactional.sql
-- Raw transactional tables populated by the "direct" ingester
-- (python/monogram_etl/ingesters/direct.py — SQL INSERT path, near real-time).
-- Idempotent with CREATE IF NOT EXISTS so this can run before every batch.

USE ROLE INGEST;
USE WAREHOUSE INGEST;
USE DATABASE INGEST;
USE SCHEMA INGEST;

CREATE TABLE IF NOT EXISTS SALES_DATA (
    SALE_ID        VARCHAR(10),
    SALE_DATE      DATE,
    CUSTOMER_ID    VARCHAR(10),
    PRODUCT_ID     VARCHAR(10),
    PRODUCT_NAME   VARCHAR(100),
    QUANTITY       INTEGER,
    UNIT_PRICE     DECIMAL(10,2),
    TOTAL_AMOUNT   DECIMAL(10,2),
    CHANNEL        VARCHAR(20),
    STORE_ID       VARCHAR(10),
    COUNTRY        VARCHAR(50),
    CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS RETURNS_DATA (
    RETURN_ID      VARCHAR(10),
    SALE_ID        VARCHAR(10),
    CUSTOMER_ID    VARCHAR(10),
    PRODUCT_ID     VARCHAR(10),
    RETURN_DATE    DATE,
    REASON         VARCHAR(50),
    CONDITION      VARCHAR(20),
    REFUND_AMOUNT  DECIMAL(10,2),
    REFUND_METHOD  VARCHAR(30),
    PROCESSED_BY   VARCHAR(100),
    STATUS         VARCHAR(20),
    NOTES          VARCHAR(500),
    CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS REVIEWS_DATA (
    REVIEW_ID          VARCHAR(10),
    PRODUCT_ID         VARCHAR(10),
    CUSTOMER_ID        VARCHAR(10),
    RATING             INTEGER,
    TITLE              VARCHAR(100),
    COMMENT            VARCHAR(1000),
    REVIEW_DATE        DATE,
    VERIFIED_PURCHASE  BOOLEAN,
    HELPFUL_VOTES      INTEGER,
    STATUS             VARCHAR(20),
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS INVENTORY_DATA (
    INVENTORY_ID         VARCHAR(10),
    PRODUCT_ID           VARCHAR(10),
    STORE_ID             VARCHAR(10),
    CURRENT_STOCK        INTEGER,
    RESERVED_STOCK       INTEGER,
    REORDER_LEVEL        INTEGER,
    MAX_STOCK_LEVEL      INTEGER,
    LAST_RESTOCKED       DATE,
    NEXT_DELIVERY_DATE   DATE,
    WAREHOUSE_LOCATION   VARCHAR(50),
    CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
