-- 02_raw_reference.sql
-- Raw reference tables populated by the "snowpipe" ingester
-- (python/monogram_etl/ingesters/snowpipe.py — Parquet + COPY path, batch).
-- Idempotent with CREATE IF NOT EXISTS.

USE ROLE INGEST;
USE WAREHOUSE INGEST;
USE DATABASE INGEST;
USE SCHEMA INGEST;

CREATE TABLE IF NOT EXISTS PRODUCTS_DATA_SNOWPIPE (
    PRODUCT_ID     VARCHAR(20) NOT NULL,
    NAME           VARCHAR(255) NOT NULL,
    CATEGORY       VARCHAR(100),
    SUBCATEGORY    VARCHAR(100),
    BRAND          VARCHAR(100),
    MATERIAL       VARCHAR(100),
    COLOR          VARCHAR(50),
    PRICE          NUMBER(10,2),
    COST           NUMBER(10,2),
    WEIGHT_KG      NUMBER(8,2),
    DIMENSIONS_CM  VARCHAR(50),
    SUPPLIER_ID    VARCHAR(20),
    CREATED_DATE   DATE,
    LAST_UPDATED   DATE,
    IS_ACTIVE      BOOLEAN,
    SKU            VARCHAR(50),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS CUSTOMERS_DATA_SNOWPIPE (
    CUSTOMER_ID          VARCHAR(20) NOT NULL,
    FIRST_NAME           VARCHAR(100) NOT NULL,
    LAST_NAME            VARCHAR(100) NOT NULL,
    EMAIL                VARCHAR(255),
    PHONE                VARCHAR(50),
    DATE_OF_BIRTH        DATE,
    GENDER               VARCHAR(10),
    ADDRESS              VARCHAR(500),
    SEGMENT              VARCHAR(50),
    REGISTRATION_DATE    DATE,
    LAST_PURCHASE_DATE   DATE,
    TOTAL_ORDERS         NUMBER(10,0),
    LIFETIME_VALUE       NUMBER(12,2),
    PREFERRED_CHANNEL    VARCHAR(50),
    MARKETING_CONSENT    BOOLEAN,
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE IF NOT EXISTS SUPPLIERS_DATA_SNOWPIPE (
    SUPPLIER_ID         VARCHAR(20) NOT NULL,
    NAME                VARCHAR(255) NOT NULL,
    CONTACT_PERSON      VARCHAR(255),
    EMAIL               VARCHAR(255),
    PHONE               VARCHAR(50),
    ADDRESS             VARCHAR(500),
    SPECIALTY           VARCHAR(255),
    LEAD_TIME_DAYS      NUMBER(5,0),
    MINIMUM_ORDER       NUMBER(10,2),
    PAYMENT_TERMS       VARCHAR(100),
    QUALITY_RATING      NUMBER(3,2),
    ESTABLISHED_DATE    DATE,
    IS_ACTIVE           BOOLEAN,
    PRIMARY KEY (SUPPLIER_ID)
);

CREATE TABLE IF NOT EXISTS STORES_DATA_SNOWPIPE (
    STORE_ID         VARCHAR(20) NOT NULL,
    STORE_NAME       VARCHAR(255) NOT NULL,
    MANAGER_NAME     VARCHAR(255),
    ADDRESS          VARCHAR(500),
    CITY             VARCHAR(100),
    COUNTRY          VARCHAR(100),
    PHONE            VARCHAR(50),
    EMAIL            VARCHAR(255),
    OPENING_DATE     DATE,
    STORE_SIZE_SQM   NUMBER(10,2),
    IS_ACTIVE        BOOLEAN,
    PRIMARY KEY (STORE_ID)
);

CREATE TABLE IF NOT EXISTS PROMOTIONS_DATA_SNOWPIPE (
    PROMOTION_ID       VARCHAR(20) NOT NULL,
    NAME               VARCHAR(255) NOT NULL,
    DESCRIPTION        VARCHAR(500),
    DISCOUNT_TYPE      VARCHAR(50),
    DISCOUNT_VALUE     NUMBER(8,2),
    START_DATE         DATE,
    END_DATE           DATE,
    MINIMUM_PURCHASE   NUMBER(10,2),
    IS_ACTIVE          BOOLEAN,
    CREATED_DATE       DATE,
    PRIMARY KEY (PROMOTION_ID)
);
